language: python
python:
  - "3.6"
install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
services:
  - postgresql
env:
  global:
    - APP_SETTINGS=testing
before_script:
  - psql -c 'create database test_sendIT;' -U postgres

script:
  - py.test --cov-config .coveragerc --cov=Api
  - coverage report
after_success:
  - coveralls
  - pytest
